services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - '${APP_DEV_PORT}:${APP_DEV_PORT}'
    volumes:
      - .:/app
      - /app/node_modules
    depends_on:
      - json-server
    environment:
      - APP_DEV_PORT=${APP_DEV_PORT}
  json-server:
    image: node:18
    working_dir: /data
    volumes:
      - ./data:/data
    ports:
      - '${JSON_SERVER_PORT}:${JSON_SERVER_PORT}'
    environment:
      - JSON_SERVER_PORT=${JSON_SERVER_PORT}
    command: >
      bash -c "npm install -g json-server &&
               json-server db.json --host 0.0.0.0 --port ${JSON_SERVER_PORT}"

